version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgis/postgis:12-3.1
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - ~/postgresdb:/var/lib/postgresql/data

