version: '3.7'

services:

  postgres:
    image: postgis/postgis:12-3.1
    networks:
      - webnet
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432
    volumes:
      - /opt/postgresdb:/var/lib/postgresql/data

  2mapMigrations:
    image: docker.pkg.github.com/mikhail-angelov/2maps/2maps-migration:latest
    networks:
      - webnet
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres:postgres
    command: npm run migration:run

networks:
  webnet:
