version: '3.3'

services:
  postgres:
    image: postgis
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ~/postgresdb:/var/lib/postgresql/data

