version: '3.7'

services:

  mapnn:
    image: mangelov/mapnn-tiles:latest
    container_name: "mapnn"
    networks:
      - webnet
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm start
    volumes:
        - ./data:/opt/app/data:rw

networks:
  webnet:
