name: ci
on: push
jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x

    - name: test server
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
        docker pull docker.pkg.github.com/mikhail-angelov/2maps/postgis:16-3.4-alpine
        npm ci
        npm test

     #Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Publish Docker Image to GPR
      run: |
        docker -v
        echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
        docker build . --tag docker.pkg.github.com/mikhail-angelov/2maps/2maps:latest --cache-from docker.pkg.github.com/mikhail-angelov/2maps/2maps:latest
        docker push docker.pkg.github.com/mikhail-angelov/2maps/2maps:latest
        docker build -f ./DockerfileMigration . --tag docker.pkg.github.com/mikhail-angelov/2maps/2maps-migration:latest --cache-from docker.pkg.github.com/mikhail-angelov/2maps/2maps-migration:latest
        docker push docker.pkg.github.com/mikhail-angelov/2maps/2maps-migration:latest
